replicaCount: 1

provider: "digitalocean"
region: "lon1"

# provider: "gce"
# zone: "us-central1-a"
# gceProjectId: "<Your GCP Project ID>"

#provider: "packet"
#region: "ams1"
# packetProjectId: "project-id"
accessKeyFile: "/var/secrets/inlets/inlets-access-key"

# Obtain from https://github.com/alexellis/inlets-pro-pkg
inletsProLicense: ""

annotatedOnly: false

image: "inlets/inlets-operator:0.5.2"
pullPolicy: "IfNotPresent"
clientImage: "inlets/inlets:2.6.3"
proClientImage: "alexellis2/inlets-pro:0.4.3"

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
