[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/inlets/inletsctl"
  version = "0.3.0"

[[override]]
  name = "golang.org/x/sys"
  branch = "master"

[[override]]
  name = "golang.org/x/oauth2"
  branch = "master"
