---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inlets-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inlets-operator-rw
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["inlets.inlets.dev"]
  resources: ["tunnels", "tunnels/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "services/status", "services/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inlets-operator-rw
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inlets-operator-rw
subjects:
- kind: ServiceAccount
  name: inlets-operator
  namespace: {{ .Release.Namespace }}
